-- schema-test.sql - Structure exacte comme PostgreSQL
CREATE TABLE IF NOT EXISTS domaine (
                                       iddomaine BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       description VARCHAR(255),
    image VARCHAR(255),
    nomdomaine VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS categorie (
                                         idcategorie BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         description VARCHAR(255),
    image VARCHAR(255),
    nomcategorie VARCHAR(255),
    iddomaine BIGINT NOT NULL,
    FOREIGN KEY (iddomaine) REFERENCES domaine(iddomaine)
    );

CREATE TABLE IF NOT EXISTS client (
                                      idclient BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      dateinscription TIMESTAMP,
                                      email VARCHAR(255) UNIQUE,
    enabled BOOLEAN NOT NULL,
    google_id VARCHAR(255) UNIQUE,
    motdepasse VARCHAR(255),
    nom VARCHAR(255),
    pays VARCHAR(255),
    photoprofil VARCHAR(255),
    prenom VARCHAR(255),
    tel VARCHAR(255),
    ville VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS produit (
                                       idproduit BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       a_expertise BOOLEAN NOT NULL,
                                       datepublication TIMESTAMP,
                                       description VARCHAR(255),
    etat VARCHAR(255),
    nom VARCHAR(255),
    prixdebut DOUBLE PRECISION,
    prixfin DOUBLE PRECISION,
    idclientacheteur BIGINT,
    idcategorie BIGINT,
    idclient BIGINT,
    FOREIGN KEY (idclient) REFERENCES client(idclient),
    FOREIGN KEY (idcategorie) REFERENCES categorie(idcategorie),
    FOREIGN KEY (idclientacheteur) REFERENCES client(idclient)
    );

CREATE TABLE IF NOT EXISTS produit_image (
                                             idimage BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             url VARCHAR(255),
    produit_idproduit BIGINT,
    FOREIGN KEY (produit_idproduit) REFERENCES produit(idproduit)
    );

CREATE TABLE IF NOT EXISTS interaction (
                                           idinteraction BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           date TIMESTAMP NOT NULL,
                                           idclient BIGINT NOT NULL,
                                           idproduit BIGINT NOT NULL,
                                           FOREIGN KEY (idclient) REFERENCES client(idclient),
    FOREIGN KEY (idproduit) REFERENCES produit(idproduit),
    UNIQUE(idclient, idproduit) -- Empêche les doublons
    );