spring.application.name=marketplace_auctions

# --- Configuration de la BDD PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/bazart
spring.datasource.username=postgres
spring.datasource.password=1234

# Dialecte JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


# Cache (activer le cache Spring, optionnel)
spring.cache.type=simple

app.jwt.secret=MaSuperCleSecreteUltraLongueEtImprevisible_1234567890!@#$%

spring.security.oauth2.client.registration.*=false

# Logs pour debug
logging.level.org.springframework.security=DEBUG
logging.level.com.marketplace=DEBUG
logging.level.org.springframework.mail=DEBUG

##spring.mail.host=sandbox.smtp.mailtrap.io
##spring.mail.port=2525
##spring.mail.username=982d69521e49a0
##spring.mail.password=57e68e458f1b93
##spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.starttls.enable=true
##spring.mail.properties.mail.smtp.starttls.required=true
# Expediteur visible dans les mails
##app.mail.from=no-reply@bazart.com
#(Optionnel) Adresse de reponse
##app.mail.reply.to=support@bazart.com
# Augmenter la limite d'upload (exemple : 10MB)
# Augmenter la limite d'upload (exemple : 10MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chebila.douae@gmail.com
spring.mail.password=cktg mmjp uzis rxsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true