spring.application.name=marketplace_auctions

# --- Configuration de la BDD PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/bazart
spring.datasource.username=postgres
spring.datasource.password=1234

# Dialecte JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


# Cache (activer le cache Spring, optionnel)
spring.cache.type=simple

app.jwt.secret=MaSuperCleSecreteUltraLongueEtImprevisible_1234567890!@#$%

spring.security.oauth2.client.registration.*=false

# Logs pour debug
logging.level.org.springframework.security=DEBUG
logging.level.com.marketplace=DEBUG


spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=982d69521e49a0
spring.mail.password=57e68e458f1b93
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Exp�diteur visible dans les mails
app.mail.from=no-reply@bazart.com

#(Optionnel) Adresse de r�ponse
app.mail.reply.to=support@bazart.com