spring.application.name=marketplace_auctions

# --- Configuration de la BDD PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/bazart
spring.datasource.username=postgres
spring.datasource.password=admin

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
# Dialecte JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


# Cache (activer le cache Spring, optionnel)
spring.cache.type=simple

app.jwt.secret=MaSuperCleSecreteUltraLongueEtImprevisible_1234567890!@#$%

spring.security.oauth2.client.registration.*=false

# Logs pour debug
logging.level.org.springframework.security=DEBUG
logging.level.com.marketplace=DEBUG